networks:
  hubzilla:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

services:
  hub_db:
    container_name: hubzilla_database       # ARBITARY (user can/should change)
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    #healthcheck:
    #  test: ["/usr/bin/mysql --user=${DB_USER} --password=${DB_PASSWORD} --execute \"SHOW DATABASES;\""]
    #  interval: 10s
    #  timeout: 5s
    #  retries: 5
    networks:
      hubzilla:
        ipv4_address: 172.20.0.30
    volumes:
        - db_data:/var/lib/postgresql/data

  hub_web:
    container_name: hubzilla_webserver      # ARBITARY (user can/should change)
    image: nginx:1.25.3-alpine
    restart: unless-stopped
    depends_on:
      hub:
        condition: service_healthy
      hub_cron:
        condition: service_started
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_config:/etc/nginx/conf.d:ro
      - ssl_certs:/etc/nginx/ssl:ro
      - web_root:/var/www/html:Z            # Retain the capital Z (SELinux permission issues)
    command: >
      sh -c "nginx -g 'daemon off;' & 
             sleep 20 && 
             nginx -s reload && 
             wait"
    networks:
      hubzilla:
        ipv4_address: 172.20.0.10

  hub:
    container_name: hubzilla_itself         # ARBITARY (user can/should change)
    build: .
    # image: "dhitchenor/hubzilla:${VER_FULL}"
    restart: unless-stopped
    depends_on:
      - hub_db
    env_file:
      - .env
    networks:
      hubzilla:
        ipv4_address: 172.20.0.20
    volumes:
      - web_root:/var/www/html:Z            # Retain the capital Z (SELinux permission issues)
      - ssl_certs:/var/ssl-shared
      - nginx_config:/var/nginx-config
      - /mnt/c/Users/mattb/AppData/Local/mkcert:/root/.local/share/mkcert:ro
    healthcheck:
      test: ["CMD-SHELL", "test -f /var/nginx-config/default.conf || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  hub_cron:
    container_name: hubzilla_cronjob        # ARBITARY (user can/should change)
    build: .
    # image: "dhitchenor/hubzilla:${VER_FULL}"
    restart: unless-stopped
    depends_on:
      - hub_db
    env_file:
      - .env
    networks:
      hubzilla:
        ipv4_address: 172.20.0.40
    command: ["crond", "-f"]

  stalwart:
    container_name: hubzilla_mailserver
    image: stalwartlabs/stalwart:latest
    restart: unless-stopped
    ports:
      - "25:25"     # SMTP
      - "143:143"   # IMAP
      - "993:993"   # IMAPS
      - "465:465"   # SMTP over SSL
      - "587:587"   # SMTP submission
      - "8080:8080" # Web admin
    volumes:
      - stalwart_data:/opt/stalwart
      - ./stalwart-config/config.toml:/opt/stalwart/etc/config.toml:ro
    environment:
      - STALWART_HOSTNAME=mail.localhost
    networks:
      hubzilla:
        ipv4_address: 172.20.0.50

volumes:
  db_data:
  web_root:
  ssl_certs:
  nginx_config:
  stalwart_data:
