#!/bin/bash

# Stalwart SSL Certificate Setup Function
# Copies mkcert certificates from shared volume and configures Stalwart to use them
setup_stalwart_ssl() {
	echo "======== CONFIGURING: Stalwart SSL certificates ========"
	
	# Wait for SSL certificates to be generated by main container
	local max_wait=30
	local count=0
	
	while [ ! -f "/var/ssl-shared/${DOMAIN}.pem" ] || [ ! -f "/var/ssl-shared/${DOMAIN}-key.pem" ]; do
		if [ $count -ge $max_wait ]; then
			echo "ERROR: SSL certificates not found after ${max_wait} seconds"
			echo "Make sure the main Hubzilla container has generated certificates"
			return 1
		fi
		echo "Waiting for SSL certificates to be generated... (${count}/${max_wait})"
		sleep 1
		count=$((count + 1))
	done
	
	# Create SSL directory in Stalwart
	mkdir -p /opt/stalwart/etc/ssl
	
	# Copy certificates from shared volume
	echo "Copying SSL certificates to Stalwart..."
	cp /var/ssl-shared/${DOMAIN}.pem /opt/stalwart/etc/ssl/${DOMAIN}.pem
	cp /var/ssl-shared/${DOMAIN}-key.pem /opt/stalwart/etc/ssl/${DOMAIN}-key.pem
	
	# Set proper permissions
	chmod 644 /opt/stalwart/etc/ssl/${DOMAIN}.pem
	chmod 600 /opt/stalwart/etc/ssl/${DOMAIN}-key.pem
	
	# Verify certificates were copied
	if [ -f "/opt/stalwart/etc/ssl/${DOMAIN}.pem" ] && [ -f "/opt/stalwart/etc/ssl/${DOMAIN}-key.pem" ]; then
		echo "======== SUCCESS: Stalwart SSL certificates configured ========"
		return 0
	else
		echo "======== ERROR: Failed to copy SSL certificates ========"
		return 1
	fi
}
