#!/bin/bash

# Stalwart SSL Certificate Setup Function for Local Development
# Copies mkcert certificates from Traefik shared volume and configures Stalwart to use them
setup_stalwart_ssl() {
	echo "======== CONFIGURING: Stalwart SSL certificates (Local Dev) ========"
	
	# Use MAIL_DOMAIN if set, otherwise fall back to DOMAIN for backwards compatibility
	CERT_DOMAIN="${MAIL_DOMAIN:-$DOMAIN}"
	
	# Wait for SSL certificates to be generated by Traefik container
	local max_wait=30
	local count=0
	
	# Check for certificates generated by Traefik (these use DOMAIN, not MAIL_DOMAIN)
	while [ ! -f "/var/ssl-shared/${DOMAIN}.pem" ] || [ ! -f "/var/ssl-shared/${DOMAIN}-key.pem" ]; do
		if [ $count -ge $max_wait ]; then
			echo "ERROR: SSL certificates not found after ${max_wait} seconds"
			echo "Make sure the Traefik container has generated mkcert certificates"
			return 1
		fi
		echo "Waiting for SSL certificates to be generated... (${count}/${max_wait})"
		sleep 1
		count=$((count + 1))
	done
	
	# Create SSL directory in Stalwart
	mkdir -p /opt/stalwart/etc/ssl
	
	# Copy certificates from shared volume
	# Source uses DOMAIN (from Traefik), destination uses MAIL_DOMAIN (for Stalwart config)
	echo "Copying SSL certificates to Stalwart..."
	cp /var/ssl-shared/${DOMAIN}.pem /opt/stalwart/etc/ssl/${CERT_DOMAIN}.pem
	cp /var/ssl-shared/${DOMAIN}-key.pem /opt/stalwart/etc/ssl/${CERT_DOMAIN}-key.pem
	
	# Set proper permissions
	chmod 644 /opt/stalwart/etc/ssl/${CERT_DOMAIN}.pem
	chmod 600 /opt/stalwart/etc/ssl/${CERT_DOMAIN}-key.pem
	
	# Verify certificates were copied
	if [ -f "/opt/stalwart/etc/ssl/${CERT_DOMAIN}.pem" ] && [ -f "/opt/stalwart/etc/ssl/${CERT_DOMAIN}-key.pem" ]; then
		echo "======== SUCCESS: Stalwart SSL certificates configured ========"
		echo "Source: /var/ssl-shared/${DOMAIN}.pem"
		echo "Destination: /opt/stalwart/etc/ssl/${CERT_DOMAIN}.pem"
		return 0
	else
		echo "======== ERROR: Failed to copy SSL certificates ========"
		return 1
	fi
}
