name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get major version
      id: version
      env:
        repository_owner: ${{ github.repository_owner }}
        repository: ${{ github.repository }}
      run: |
        echo "::set-output name=major::$(awk -F, '{print $2}' .tags)"
        echo "::set-output name=full::$(awk -F, '{print $1}' .tags)"
        echo "Will build for: $repository_owner/$repository:latest"

    - name: Docker Setup qemu-action
      uses: docker/setup-qemu-action@v1
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1
    - name: Docker Login
      uses: docker/login-action@v1.6.0
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
        push: true
        tags: |
          ${{ github.repository_owner }}/${{ github.repository }}:latest
          ${{ github.repository_owner }}/${{ github.repository }}:${{ steps.version.outputs.full }}
          ${{ github.repository_owner }}/${{ github.repository }}:${{ steps.version.outputs.major }}
          
