name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get full version
      id: full
      run: echo "::set-output name=full::$(awk -F, '{print $1}' .tags)"
    - name: Get major version
      id: major
      run: echo "::set-output name=major::$(awk -F, '{print $2}' .tags)"

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1
    - name: Docker Login
      uses: docker/login-action@v1.6.0
      with:
        username: ${{ GITHUB_ACTOR }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
        push: true
        tags: |
          ${{ GITHUB_ACTOR }}/${{ GITHUB_REPOSITORY }}:latest
          ${{ GITHUB_ACTOR }}/${{ GITHUB_REPOSITORY }}:${{ steps.full.outputs.full }}
          ${{ GITHUB_ACTOR }}/${{ GITHUB_REPOSITORY }}:${{ steps.major.outputs.major }}
          
